name: Deploy to Netlify

on:
  push:
    branches:
      - feature/microservice

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Match your project's Node.js version

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          npm install
          netlify deploy --prod --dir=. --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ac6cd1a2-2b63-47a7-af71-17c6345e39bc
